### ISSUE TITLE
Interactive Graph is Buggy in Brave Browser

### ISSUE THREAD

**Issue by mettaseva** [oleeskild/obsidian-digital-garden#103]
### Discussed in https://github.com/oleeskild/obsidian-digital-garden/discussions/10
@oleeskild ~ Apologies if I posted this issue in the wrong location originally.

<div type='discussions-op-text'>

<sup>Originally posted by **mettaseva** November 13, 2022</sup>
@oleeskild ~ 

After working with my new site in my Brave browser, I discovered the performance of the interactive graph is not to up to par with its performance in the Edge browser:
- navigation, when it works, is slower and
- often the navigation doesn't work at all.

Is this an issue that can be resolved without too much difficulty?</div>

**Comment by jaalte** [comment]
I think it's related to HTML canvas data. I use Firefox and have it disabled by default. When I tried to grab one of the graph nodes it just panned the viewport. Once I enabled HTML canvas data it worked fine, just like in the obsidian client.

**Comment by mettaseva** [comment]
@jaalte ~ Thanks so much for your helpful feedback! I'm glad to know you've found a workaround in FireFox.

However, my goal is to create a library of resources to share publicly with others, and (ideally) I would prefer that Brave and FireFox users didn't have to make special adjustments for the graph view to work in their browser.

In light of this, I am still looking forward to feedback from @oleeskild in response to my original inquiry about the feasibility of addressing this browser display issue on the back end.

**Comment by oleeskild** [comment]
@mettaseva Thanks for reporting this.
As @jaalte correctly pointed out, this is an issue in Brave because of its privacy focus. The library I use to render the graph is called force-graph. There is an [open issue](https://github.com/vasturiano/force-graph/issues/177) in that repo about this very problem. As explained in that thread, this is a side effect of Brave trying to protect against fingerprint logging and thus is purposely reporting back wrong values for the function that is used to create the clickable links and navigation.

Users can get around it by disabling the "fingerprinting protections" feature. 

Unfortunately I won't be able to fix this, as this is the fault of the Brave Browser not following browser standards. 

Note that it works fine in Firefox. As @jaalte pointed out, it didn't work on his machine because he had **actively disabled** the canvas data setting in his browser. **By default this is enabled in Firefox.**

**Comment by exrhizo** [comment]
I fixed this for coordinape by forking
https://github.com/coordinape/coordinape/tree/main/canvas-color-tracker
