### ISSUE TITLE
Comments inside notes

### ISSUE THREAD

**Issue by Mowd** [oleeskild/obsidian-digital-garden#112]
There's a feature of Obsidian called comments that use %% to enclose comments to hide texts on the preview page.
In the current version of the digital garden, the comments block will show on the page.

**Comment by oleeskild** [comment]
Thanks for the feedback!

This should work. I just tested adding a %%some comment%% to a note, and publishing it, and it disappears from the published page. Do you have an example of this not working?

**Comment by oleeskild** [comment]
Thank you! Turns out there was a bug if any of the comment blocks contained code blocks. The plugin needs to be smart about not stripping away comments inside code blocks, but turns out the way it was implemented did not take into account that a comment might have a codeblock inside. It should be fixed in the latest release. Thanks for letting me know about it!
