### ISSUE TITLE
[Bug] I want to distribute markdown in languages ​​other than English

### ISSUE THREAD

**Issue by 2gseer** [oleeskild/obsidian-digital-garden#136]
Hello, I'm using Digital Garden as a plug-in, but I see an issue, so I'm contacting you.
If the markdown file name is not in English, an html file is created with only the rest of the file name except for English, and an error appears when trying to distribute it. I wonder if this part will be fixed.
happy new year!

**Comment by oleeskild** [comment]
Hi! 
This happens because we are ["slugifying"](https://www.semrush.com/blog/what-is-a-url-slug/) the URL of your notes. Unfortunately this means that non-english characters gets removed. But you can turn it off in the settings: https://dg-docs.ole.dev/getting-started/05-other-settings/#slugify-note-url
You need to republish the files after changing that setting. They should appear in the "Changed" section in the publication center.

Let me know if you run into any problems.

**Comment by oleeskild** [comment]
Did you get this to work @2gseer ?

**Comment by 2gseer** [comment]
It worked out fine. thank you

**Comment by NiuHK** [comment]
The same problem now exists for the title link in the article. Even if slugify is turned off, the title link will still be truncated at the first non-English character, which causes confusion when using the link.
