### ISSUE TITLE
Hosting options

### ISSUE THREAD

**Issue by opheliagame** [oleeskild/obsidian-digital-garden#177]
I see on the documentation page that Github Pages as an option for hosting is a work in progress (https://dg-docs.ole.dev/advanced/hosting-alternatives/) but since it isn't present on the projects kanban board (https://github.com/users/oleeskild/projects/1/views/1), I was wondering if maybe some help is required. I could volunteer in such a case :)

**Comment by oleeskild** [comment]
I haven't yet started on any of the non-supported ones. So any help would be greatly appreciated. 😄 The two things that needs to be in place for supporting a new platform is a redirect to /404 when the page isn't found, and a serverless search function.
As an example to get you started, for Vercel, the search is defined in [this file](https://github.com/oleeskild/digitalgarden/blob/main/api/search.js) and the 404 routing is defined in [this file](https://github.com/oleeskild/digitalgarden/blob/main/vercel.json)

**Comment by oleeskild** [comment]
Very cool! Perhaps offline search is a better solution in general, as it would make it much easier to support any hosting platform. The one worry I have is that the search index would get very large for sites with lots of notes, meaning people would need to download a lot for search to work. But I haven't really looked into if this is actually a problem or not in practive. Perhaps this could be a setting, where users can toggle whether they want the server search or the offline, client-side search. 

I also just got an idea for the 404 page. We could point all the links that doesn't lead anywhere to the 404 page in the build step, instead of doing that in the hosting provider settings. If we did those two things, it should be trivial to move between hosting platforms.

**Comment by oleeskild** [comment]
Awesome! I have to approve the PR before it is added to the repository, so you there is no way for you to mess things up. So don't worry about that! You should be able to create a PR based on your forks of the two repositories, as described here: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork

If you've only made changes to your own garden, which by default is not a fork, you probably need to first create a fork from the digitalgarden repo, and then just manually copy the files you have changed  from your garden to your newly forked repository, before creating a Pull Request to the original repo. 

After you've done this I will look through the changes, and let you know if anything needs to change or similar. Let me know if you need any more guidance in creating the PRs.

As mentioned, there is no way for you to mess up anything for anyone, so just try creating a Pull Request and we'll go from there 😄
