### ISSUE TITLE
themes in appearance setting seems not working

### ISSUE THREAD

**Issue by dalezys** [oleeskild/obsidian-digital-garden#179]
Sorry to bother you with this stupid question. I just build my own digital garden with netlify and this plugin today. Everything works perfect except when I tried to change the theme in the appearance setting. 

I tried multiple different themes with `dark` base theme. All of them were successfully built and deployed. However, except for the default one, other themes (blue topaz, minimal, prism, obsidian nord ...)  just looks the same, nothing changed. Did I miss any steps?

Thank you in advance
Dale

**Comment by CubityFirst** [comment]
Yeah, this seems to be happening to me aswell.

![image](https://user-images.githubusercontent.com/14070268/216043790-f0046db4-5195-4110-92cb-64f751bb40c7.png)

I'm on the latest template but no themes are applying,

The 404 page also has text in the top left showing style information but it might be because it's not loading either?

![image](https://user-images.githubusercontent.com/14070268/216043941-38952ffb-47cc-4f25-970e-7597e5338649.png)

**Comment by oleeskild** [comment]
Not a stupid question at all. It seems like it’s a bug. I think I might know whats going on here. I’ll try to get a fix out some time today. I’ll let you know here when it’s available

**Comment by CubityFirst** [comment]
Themes are applying to the main page, notes etc, but the 404 page is still unthemed & has the text in the top left as seen before.

**Comment by dalezys** [comment]
Thank you so much for your prompt response! Now I can play around with the themes! XD

**Comment by oleeskild** [comment]
Right, forgot about the 404 page. I've released a new version again of the template, where this should be fixed. Thanks for reporting back 👌
