### ISSUE TITLE
[QUESTION] Pushing to Vercel in batches?

### ISSUE THREAD

**Issue by ludwikc** [oleeskild/obsidian-digital-garden#211]
Vercel app in free plan offers up to 100 Deployments per Day. 

If I want to publish 100 notes in one "Publish Multiple Notes" action in Obsidian - will it use 100 or 1 deployment run?

**Comment by oleeskild** [comment]
I'm actually not sure. Previously the default hosting services was Netlify, and there they batched together commits if they were pushed in rapid succession, so that you would end up with 1 build even if you published 100 notes. But I haven't looked into how this mechanism works in Vercel. I'll see if I can figure it out in their documentation. If they don't do the same as Netlify, I might have to look into changing the publish multiple notes command to instead publish all the notes as a single commit.

**Comment by oleeskild** [comment]
Tested this today: Published 180 notes using the "Publish Multiple Notes" command, which essentially creates 180 commits. Looking at Vercel, they started a build of the first commit. Then, when that was finished, they started building all the commits that had been added in the meantime. In total it resulted in 5 deployments. So this shouldn't be a problem.
