### ISSUE TITLE
Broken image after updating homepage

### ISSUE THREAD

**Issue by amperag** [oleeskild/obsidian-digital-garden#226]
After re-publishing the homepage of my digital garden the main image broke:

`Hannah&Lukas (39).jpg`

![image](https://user-images.githubusercontent.com/61867589/224553161-dc479149-3fb0-4cbf-95cd-367f10265f12.png)

Digital garden: https://www.alberer.contact/

**Comment by shinanqu** [comment]
Can you delete it, perhaps rename it and drop it again into Obsidian?

Also I am using the Imgur Plugin. That way the Obsidian Vault does not get clogged up with images.
https://github.com/gavvvr/obsidian-imgur-plugin

However, on the other side I am worried about SEO, because the Imgur images lose their original name, so it's not a perfect solution.

If this is the only image that is broken and you can't make it work, you can upload only this one image to Imgur and link it in Obsidian
![[ ]]

**Comment by shinanqu** [comment]
That's a strange issue, really have no idea, sorry :-( I can only suggest hosting the image on Imgur. Good luck!

**Comment by yannick42** [comment]
I think I have the same problem, on any newly published notes which contains an image with a space "%20" in its filename (?)

I get a 404 error

(I have a .gif or other .png in the same directory `/img/user/...` without spaces, which works correctly)

**Comment by oleeskild** [comment]
I _think_ I've found the bug. As you correctly noticed @yannick42, I believe this happened when an image had a filepath that contained a space. I think the latest version, 2.42.2, of the plugin should fix it. Can you test @amperag, and report back if that solved it for you or not?

**Comment by yannick42** [comment]
It works for me, thanks ! :)
