### ISSUE TITLE
Any ideas how to add search widget to digital garden?

### ISSUE THREAD

**Issue by assopri** [oleeskild/obsidian-digital-garden#24]
Thank you for your cool product! Any ideas how to add search widget?

**Comment by oleeskild** [comment]
I will look into this. I do already have some thoughts on how to add it. 

Do you have any thoughts on how it should work? Would it be best if it could be enabled in the plugin settings and then appear on every note in your site, or where you envisioning something else?

**Comment by assopri** [comment]
Thank you for fast answer! Actyally, for my case the best search mechanics is the one I found at Zola implementation: https://peteryuen.netlify.app/ . I mean when the search is present on all website pages. As for widget behavior - I like the Zola implementation as well:
![image](https://user-images.githubusercontent.com/73235464/161490885-61c9f6a6-d168-48ea-b7a6-dfc2deb2bd3e.png)

**Comment by assopri** [comment]
btw, I found images are successfully transfered to netlify website. In which folder on git are they saved? (sorry if needed create separate topic for this question)?

**Comment by oleeskild** [comment]
Great input. The zola implementation looks nice. I will take a closer look at it and try to come up with something. 

Regarding the image part: the images are actually just encoded into base64 and embedded directly in the note itself. If you go to the src/site/notes folder in your repo and find a note that has an image, you will see that there is a long string there, instead of an image link.

**Comment by assopri** [comment]
Thank you, got it!

**Comment by meleu** [comment]
+1 for a searching feature.

I tried several "publish your obsidian vault as a digital garden" approaches that are emerging recently, and I really like this one because it's very clean. Only a pretty damn simple webpage is what we need. But... for those who have thousands of notes, a search widget starts to become mandatory...

Besides the "obsidian-zola" mentioned above, there's also this one here to get some inspiration: https://quartz.jzhao.xyz/

**Comment by aravindk100** [comment]
Just set this plugin up and I was amazed how easy and clean this was. Thank you. Looking forward to the search capability.

**Comment by shmuga** [comment]
I have built a basic search on lunrjs here https://github.com/oleeskild/digitalgarden/pull/12

It builds at the site build step the index and then uses netlify as API provider for search. The search page is maybe too simple but I didn't want to spend too much time on it

**Comment by oleeskild** [comment]
I've merged @shmuga's changes and added a new "Enable search" option in the plugin. It should add a search bar which you can click to bring up a popup allowing you to search all your notes. It can also be triggered by pressing CTRL + K or CMD + K on mac. 
Remember to first update the plugin to the lates version, then use the "Create PR" button to update to the latest template. 

Thanks a lot to @shmuga for doing most of the heavy lifting and creating a PR 🙌
