### ISSUE TITLE
[discussion] do only one commit when publishing multiple notes

### ISSUE THREAD

**Issue by meleu** [oleeskild/obsidian-digital-garden#29]
I'm migrating a bunch of notes from an old vault to my new digital garden. I published them and noticed in the repository's commit history that each single note were added in an individual commit ([example here](https://github.com/meleu/dg/commits/main)).

From the end-user point of view it's insignificant. But as developer, seeing that it triggered a bunch of events on netlify makes me feel like a wasted use of (free) resources.

I'm not a JavaScript/TypeScript person and I'm not sure about the amount of coding effort to parse all files and group them in a single git commit.

Feel free to close this issue if such behavior is like that "by design".

**Comment by meleu** [comment]
On the same topic, I've just noticed that when I update the theme without changing the favicon, the plugin creates an empty commit for the favicon.

**Comment by oleeskild** [comment]
On the favicon issue: What is happening is that whenever you leave the favicon path blank, the plugin gets the favicon of the original digitalgarden repo and commits it to your repository. If you are already using that favicon, the result is that the commit is empty as the contents are identical. 

When I find the time I'll make this setting a bit smarter, so that it doesn't touch the favicon if the setting didn't change after opening the theme settings.

**Comment by meleu** [comment]
> The benefits of each "publish" being a commit is that the intention is a bit clearer in the commit history. If you publish multiple note at the same time, that are linked together, the single commit makes it clear that all these notes is actually one "unit".

Indeed that makes a lot of sense. You made me change my mind.

The use case that made me face the "issue" was while I was migrating a whole bunch of notes. That most likely will happen when I'm starting a new digital garden. But during the day-to-day use I very much prefer to have individual commits so I can easily revert them for a specific file.

IMO this discussion can be closed.

I'm gonna open a new one about the empty favicon commit.
