### ISSUE TITLE
Inline codes in Admonition render falsely

### ISSUE THREAD

**Issue by hxhc** [oleeskild/obsidian-digital-garden#30]
Hello, I just find a little bug in rendering the inline codes in Admonitions.
For example of the below admonition, It renders like [this](https://hxhc-notes.netlify.app/publish/test/).
The inline code `Eigen` was rendered as a total line. But the code blocks in admonitions are rendered correctly.

```ad-note
`Eigen` renders falsely. 
~~~cpp
`Eigen` in code block render fails.
~~~
```

Also, the admonition is officially supported as "callout" by Obsidian. It seems that the plugin does not support the callout at this time. But currently I think the admonition is good enough, and it may take a lot of time to support the callout.

**Comment by oleeskild** [comment]
I've pushed out [changes to the template](https://github.com/oleeskild/digitalgarden/releases/tag/1.12.0) that adds support for the new obsidian callout feature.  This also fixes the inline-code rendering issues, but only for the callout syntax. 

If you're using the old admonitions syntax it will still render inline code as a full line. This is because of the way the language-parser is working. As the old syntax treats the admonititions as a code-snippet, there are some classes added to any code inside it automatically. It would require a bit of work to get around this. 

As callout blocks seems to be the way to do admonitions moving forwards, I'll leave it as it is for now. Converting old admonitions blocks to new callout blocks should be trivial to do with the latest admonition plugin update anyway.

**Comment by hxhc** [comment]
Thanks for your quick response and solution. I really like this plugin not only for its superiority but also for your kind help. I'd like to introduce this plugin in a Chinese Obsidian forum to make more people know this great plugin.

**Comment by oleeskild** [comment]
Happpy to hear that! That would be great 😄
