### ISSUE TITLE
Backlinks?

### ISSUE THREAD

**Issue by dr-code** [oleeskild/obsidian-digital-garden#31]
Thank you for this digital garden!

Two questions that I had:
1. Is there a way to have backlinks similar to obsidian?
2. If I did not want to use Netlify and wanted to use GitHub Pages, how does that change the instructions.

Thanks in advance.

**Comment by gmuller** [comment]
I second this, I was actually looking at the code today to see how hard it would be to make this work. Making a map of all published notes and creating a section at the bottom of each published page with the referenced published notes may work.

**Comment by oleeskild** [comment]
1. Yes, been thinking about adding this for a while. It shouldn't be too hard as the obsidian plugin API makes it trivial to retrieve all backlinks for a note, so I could just add it to the frontmatter before pushing it to github, and using that when generating the HTML. 

People seem to want different features from the plugin, so I'm currently in the process of adding a way to add global settings which acts as a default for all note, while still allowing you to overwrite specific notes it in the frontmatter. 
I think enabling backlinks should be one of these settings, so I'll add it as soon as the global settings feature is in place. 

2. The plugin only communicates with GitHub, and has no knowledge of netlify whatsoever. The netlify integration only works because netlify automatically listens to any changes in the repo. So if you wanted to use GitHub pages instead, you could skip using the "Deploy to netlify"-button and instead fork the repository. Then make whatever changes is neccessary to configure GitHub pages. I haven't used it myself so I don't have any knowledge of how to set it up, but I imagine it's possible to configure a build step? The config you would need to copy can be seen here: https://github.com/oleeskild/digitalgarden/blob/main/netlify.toml . So basically: Run npm install && npm run build, and point visitors to the generated dist folder. 
3. 
The netlify config also automatically sends any URL that does not correspond to a note to the 404 page. I guess you could do something similar in GitHub pages. Let me know if you figure it out, or if you're stuck on anything :)

**Comment by efemkay** [comment]
hi. just dropping a message to upvote this feature request (having backlinks). i think graph (the visual) is not as important, but "Notes Linked to This" list/table is the one most useful.

btw, i was exploring the many options available for obsidian publish alternatives for my digital garden. what i like about your setup is that it can render mathjax (including inline) - important feature for me as i do lots of statistics notes.

**Comment by oleeskild** [comment]
I've just released a new version that adds a local graph and backlinks. You'll need the latest version of both the plugin and template. 
The template can be updated via Obsidian by going to "Settings > Digital Garden > Site Template > Manage site template > Create PR"

Any feedback on what works and what you'd like to be improved would be super helpful 😄
