### ISSUE TITLE
[BUG]Image is missing after publishment

### ISSUE THREAD

**Issue by justemu** [oleeskild/obsidian-digital-garden#42]
To reproduce:

1. A MD file in the vault folder `@inbox\test.md` with an image `![](XXXXXX.png)` 
2. The image file is located in another directory of the vault.  `@assets\XXXXXX.png` for my case.
3. The page was published successfully throngh command palette, and a minute later, shown in the site. But the image is missing on the site.
4. Login to github repository to check the file.  The page file was there in `src/site/notes/`, while the image file is missing. Plus, there is not even a link of the image in the page file, which seems to be filtered out.

Is it a bug here?

**Comment by oleeskild** [comment]
Thanks for reporting this.
I simply hadn't thought of the `![](image.png)` format. I've only ever used the `![[image.png]]` format for local images. I've just released a new version of the plugin, 2.10.0, which should fix this. Let me know if it solved your issue.

**Comment by justemu** [comment]
> Thanks for reporting this. I simply hadn't thought of the `![](image.png)` format. I've only ever used the `![[image.png]]` format for local images. I've just released a new version of the plugin, 2.10.0, which should fix this. Let me know if it solved your issue.

I really appreciate and I am deeply impressed by your prompt fix.

1.  The pictures now show up!
2.  However, a page with multiple pictures comes with a problem:  the final two pictures didn't show up. I checked the source file, and here is the problem:
<img width="1076" alt="image" src="https://user-images.githubusercontent.com/20639347/166485927-5444c31b-f3b2-4e28-9360-44e136310c79.png">
Please have a look and line 6876 and line 6886. Clearly the two errorly-displaying pictures still keep markdown syntax.  I don't known why.   It should be a bug.

**Comment by oleeskild** [comment]
It seems the ones that are working are pngs, while the last two are jpgs. Is that correct?

If so it's probably an issue related to that. I'll look into it.

**Comment by justemu** [comment]
Correct. All pngs behave as expected. All jpgs keep their markdown codes.  I'm not sure what it would be for a svg file.

**Comment by ChroniclerEnigma** [comment]
I was wondering if anyone else was experiencing the jpg issue. Haven't experienced any hiccups with the png's, but i didn't start using DGP untill after this update. This has been a plugin though, so thanks for developing it!

**Comment by keerah** [comment]
Yes, the jpegs are still broken! :( Shown as base code for me
Same with SVG files, but its shown like a broken link

**Comment by oleeskild** [comment]
I've just released version 2.13.0 which should fix jpg and svg files not rendering. 
The jpg part was a bit tricky to figure out as it seems to be a bug in the library I'm using to render the markdown to html. The jpg images would not be recognized as an image, and would be treated as normal text. 
The fix was to specify the filetype to be png instead. For some reason made the library pick up on it being an image, while still managing to decode it correctly. 

SVG was simply a missing feature I hadn't implemented yet, but it has been added now and should work the same way as embedding any other images.

Sorry for taking so long implementing this, I haven't had as much time as I wanted to work on this lately. Hopefully this update will make it more usable. 
Let me know if this is working as expected now, or if there is anything I've missed :)
