### ISSUE TITLE
Backlinks with Ampersands Don't Resolve

### ISSUE THREAD

**Issue by danforbes** [oleeskild/obsidian-digital-garden#488]
Hi, thanks for the truly awesome work 🙇🏻 Some of my notes have ampersands (&) in the titles, and backlink to these notes don't resolve (404) despite the fact that the note itself does get published. For example, the link to Storage & Service on [my homepage](https://wset-notes-digital-garden.vercel.app/) doesn't resolve, but the [Storage & Service](https://wset-notes-digital-garden.vercel.app/06%20-%20Storage%20&%20Service/00%20-%20Storage%20&%20Service/) page is rendered just fine. I've turned off the slugify options. Is there a way to fix this?

**Comment by dayne** [comment]
Not an answer/solution but an explanation: 
-  `&` is used as an argument separator web / URL encodings. 
- You can use it in the URL and it works but in the guts of URL interpreters it needs to be encoded as `%26`.  
- I'm actually surprised Obsidian lets you use it in note titles. Generally I would recommend avoid using `&` (or any other reserved URI characters) in your note titles.

My gut tells me what is needed is urlencoding at some early step to avoid this issue -- which probably make sense to debug and figure out because there are other characters beyond just `&` that people might use in titles. 

Want to geek out deeply on this knowledge? Then check out the [IETF RFC 3986     Uniform Resource Identifier (URI): Generic Syntax](https://www.ietf.org/rfc/rfc3986.txt).  It really is actually pretty cool to understand this fundamental thing in our lives.
It lays out the other reserved characters - some of which Obsidian already prevents people from using in titles. 

```
reserved    = gen-delims / sub-delims
      gen-delims  = ":" / "/" / "?" / "#" / "[" / "]" / "@"
      sub-delims  = "!" / "$" / "&" / "'" / "(" / ")"
                  / "*" / "+" / "," / ";" / "="
```

**Comment by danforbes** [comment]
I have a script I'm using to prepare my vault for publishing...I could use it update titles and backlinks, but that seems a little kludgy TBH https://github.com/danforbes/wset-notes/blob/main/prepare-for-publish.ts

**Comment by oleeskild** [comment]
Sorry, this was broken in a recent refactor I did when adding better support for dataview js. I've found the issue and released an update which should fix this, so that ampersands in titles should work just fine. You need to [update the template](https://dg-docs.ole.dev/getting-started/06-updating-the-template)  for the fix. Let me know the issue was resolved or not after updating 😄
