### ISSUE TITLE
[Feature Request] Graph View 

### ISSUE THREAD

**Issue by Dhruvsr** [oleeskild/obsidian-digital-garden#62]
Just like the graph view on Obsidian as shown below, there should be a way to export it (and even if it isn't dynamic), it will be a nice touch to the digital garden.
Thanks.

**Comment by oleeskild** [comment]
Agreed, this is one of many features I want to implement. It's on my todo list, but as I'm only one person, and doing this in my free time, it will probably be a while until its implemented. Thanks for the suggestion though!

**Comment by jccastro94** [comment]
Hey! I found this repo of someone doing something similar, but with Jekyll.  It has side bar support and graph view. For anyone needing that now, they can change. 
But @oleeskild, this could help get an idea of how to do it. It's easier to copy ideas that figure it out yourself, lol. On my side, I love the simplicity of what you've done (Plugin instead of having to do outside cmd commits, easy template change through Obsidian's templates, etc), so I'll wait and even help if you need any. 
Keep up the good work!

https://github.com/maximevaillancourt/digital-garden-jekyll-template

**Comment by oleeskild** [comment]
I've just released a new version that adds a local graph and backlinks. You'll need the latest version of both the plugin and template. 
The template can be updated via Obsidian by going to "Settings > Digital Garden > Site Template > Manage site template > Create PR"

Any feedback on what works and what you'd like to be improved would be super helpful 😄
