### ISSUE TITLE
Stupid question: How should the path to a custom favicon look like?

### ISSUE THREAD

**Issue by amperag** [oleeskild/obsidian-digital-garden#99]
Sorry to even create an issue for this. But I'm feeling really dumb. I just can't get the custom favicon to work:

![image](https://user-images.githubusercontent.com/61867589/201494656-bb62b8b8-fe89-49c2-885d-4affb333dd6e.png)

How should the path look like? My favicon is stored in the following folder/path:

`[vaultname]\99 Meta\Attachments\favicon.svg`

**Comment by oleeskild** [comment]
Don't be sorry, this is exactly the kind of issues that I usually don't run into, but probably a lot of other people do.
The path should be "99 Meta/Attachments/favicon.svg", but I just tested it myself and I think you've found a bug. If the path has any spaces in any of the folder name, it won't work. 

I feel like I've seen something like a "File selector" in other plugins, where you begin to write the path, and it autocompletes. I'll see if I can figure out how to implement that, instead of free text.

**Comment by timjore** [comment]
@amperag Did you figure this out? Does `99\ Meta/Attachments/favicon.svg` work?

**Comment by oleeskild** [comment]
I've just released version 2.35.0 of the plugin, which adds a searchable dropdown menu when inputing the svg file path. @amperag, can you try to update to the latest version, and try to select the path using that, and see if that helps? Sorry for this fix has taken a while to be shipped.

**Comment by oleeskild** [comment]
Hmm, what happens if you leave the favicon path empty, and click "Apply settings to site". Does the build work then?

**Comment by oleeskild** [comment]
Did you use the latest version of the plugin when updating the template?

**Comment by oleeskild** [comment]
Hmm, this is hard to debug without having access to the garden. Would it be possible for you to make the repo with your garden public for a little bit, so I can try building it locally and see what's going wrong?

**Comment by oleeskild** [comment]
Or maybe paste the entire build log when it is failing. Looking at the others you’ve posted, I think you are missing a lot from the start? Or is that the entire build log?

**Comment by oleeskild** [comment]
Thanks! Found the error. In your "Template Digital Garden" file, you have the following tag: 
`"tags":[[99 Meta/Templates/Template Digital Garden\|]]`
The last `\|` causes some issues when generating the file used to search the garden, as "\|" isn't a valid JSON string, as the "\" is a special string in JSON.
I'll see if I can create a workaround, so that this doesn't break the build of the entire site. 

To fix the site right away, removing the "\" in that tag should fix it.

Could you post a picture or a copy-paste of how that note looks in your Obsidian vault? 
And what is the reason behind using that tag? Is there some plugin that needs that "\|" at the end or something?

**Comment by oleeskild** [comment]
I've released version 1.36.1 of the template, which should fix your issue. If you update the template to the latest version your site should start working again 🤞

**Comment by oleeskild** [comment]
Awesome, glad you finally got it working 😄 
It seems there is an obscure bug here. Because of the 
```
tags:
 - []
```
syntax, the tags translatesi into this, when reading the frontmatter: tags: [[]]. This then gets picked up as a linked file, and the plugin tries to convert it. So that is why you got that weird behaviour. I'm pushing out a fix now, where I'm ignoring whatever is in the frontmatter when converting wikilinks. Thanks for helping me figure this one out 😄

**Comment by TayraWhite** [comment]
Faced the same problem, however it just not getting it installed on my site. Updates go through normally, no interruptions and the notifications after confirmation tell me that the settings have been applied, but the icon still hasn't changed.
I am not very good at these things, for I am new at this, but I can't figure out what the cause is and why it won't install on the site.

![2024-09-02_18-24-44](https://github.com/user-attachments/assets/be6d94da-567a-4356-b313-6fb4c274018c)
![image](https://github.com/user-attachments/assets/70a68686-699f-4273-9e26-1493f191b2bd)
